title: Blog page :)
author: tris
email: tris.programming@gmail.com
description: > # this means to ignore newlines until "baseurl:"
This description has no real object or point 
# social links
twitter_username: 404 - does not exist # DO NOT include the @ character, or else the build will fail!
github_username:  JadedBracelet # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
